export enum LocationsProvider {
  LOCATION_SERVICE = 'LOCATION_SERVICE',
  LOCATION_REPOSITORY = 'LOCATION_REPOSITORY',
  LOCATION_ACTIVITY_REPOSITORY = 'LOCATION_ACTIVITY_REPOSITORY',
  LOCATION_LODGING_REPOSITORY = 'LOCATION_LODGING_REPOSITORY',
  LOCATION_PHOTO_REPOSITORY = 'LOCATION_PHOTO_REPOSITORY',
  LOCATION_TRANSPORT_REPOSITORY = 'LOCATION_TRANSPORT_REPOSITORY',
}
