export const stateRegionList = [
  { state: 'Rondônia', region: 'Norte' },
  { state: 'Acre', region: 'Norte' },
  { state: 'Amazonas', region: 'Norte' },
  { state: 'Roraima', region: 'Norte' },
  { state: 'Pará', region: 'Norte' },
  { state: 'Amapá', region: 'Norte' },
  { state: 'Tocantins', region: 'Norte' },
  { state: 'Maranhão', region: 'Nordeste' },
  { state: 'Piauí', region: 'Nordeste' },
  { state: 'Ceará', region: 'Nordeste' },
  { state: 'Rio Grande do Norte', region: 'Nordeste' },
  { state: 'Paraíba', region: 'Nordeste' },
  { state: 'Pernambuco', region: 'Nordeste' },
  { state: 'Alagoas', region: 'Nordeste' },
  { state: 'Sergipe', region: 'Nordeste' },
  { state: 'Bahia', region: 'Nordeste' },
  { state: 'Minas Gerais', region: 'Sudeste' },
  { state: 'Espírito Santo', region: 'Sudeste' },
  { state: 'Rio de Janeiro', region: 'Sudeste' },
  { state: 'São Paulo', region: 'Sudeste' },
  { state: 'Paraná', region: 'Sul' },
  { state: 'Santa Catarina', region: 'Sul' },
  { state: 'Rio Grande do Sul', region: 'Sul' },
  { state: 'Mato Grosso do Sul', region: 'Centro-Oeste' },
  { state: 'Mato Grosso', region: 'Centro-Oeste' },
  { state: 'Goiás', region: 'Centro-Oeste' },
  { state: 'Distrito Federal', region: 'Centro-Oeste' },
];
