export enum AuthProvider {
  AUTH_SERVICE = 'AUTH_SERVICE',
  LOCAL_STRATEGY = 'LOCAL_STRATEGY',
  JWT_STRATEGY = 'JWT_STRATEGY',
  JWT_SERVICE = 'JWT_SERVICE',
  REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY',
}
